### ISSUE TITLE
Cannot install LetsEncryptAuthorityX3 certificate

### ISSUE THREAD

**Issue by JoyceBabu** [freeipa/freeipa-letsencrypt#1]
I have FreeIPA docker container based on `adelton/freeipa-server`. When I run the `setup-le.sh` script, I am getting SEC_ERROR_UNKNOWN_ISSUER error.

```
[root@freeipa ipa-le]# ipa-cacert-manage install /root/ipa-le/ca/LetsEncryptAuthorityX3.pem -n letsencryptx3 -t C,,
Installing CA certificate, please wait
Not a valid CA certificate: (SEC_ERROR_UNKNOWN_ISSUER) Peer's Certificate issuer is not recognized. (visit http://www.freeipa.org/page/Troubleshooting for troubleshooting guide)
The ipa-cacert-manage command failed.
[root@freeipa ipa-le]# ipa-cacert-manage install /root/ipa-le/ca/LetsEncryptAuthorityX3.pem -n letsencryptx3 -t C,,
Installing CA certificate, please wait
Not a valid CA certificate: (SEC_ERROR_UNKNOWN_ISSUER) Peer's Certificate issuer is not recognized. (visit http://www.freeipa.org/page/Troubleshooting for troubleshooting guide)
The ipa-cacert-manage command failed.
```

According to LetsEncrypt Chain of Trust, `LetsEncryptAuthorityX3` is not cross signed by `ISGRoot X1`.

![image](https://letsencrypt.org/certs/isrg-keys.png)

So I tried installing the `(IdentTrust) DST Root CA X3`. Now I am getting SEC_ERROR_UNTRUSTED_ISSUER error.

```
[root@freeipa ipa-le]# ipa-cacert-manage install /root/ipa-le/ca/DSTRootCAX3.pem -n DSTRootCAX3 -t ,,
Installing CA certificate, please wait
CA certificate successfully installed
The ipa-cacert-manage command was successful
[root@freeipa ipa-le]# ipa-cacert-manage install /root/ipa-le/ca/LetsEncryptAuthorityX3.pem -n letsencryptx3 -t C,,
Installing CA certificate, please wait
Not a valid CA certificate: (SEC_ERROR_UNTRUSTED_ISSUER) Peer's certificate issuer has been marked as not trusted by the user. (visit http://www.freeipa.org/page/Troubleshooting for troubleshooting guide)
The ipa-cacert-manage command failed.
```

**Comment by regnauld** [comment]
Having this problem as well - plain IPA install on standard VM (not containers), CentOS 7, IPA 4.2.0

**Comment by nicki-krizek** [comment]
I'm also able to reproduce this issue. This is caused due to incorrect root cert installed and incorrect trust flags for the certificate.

**Comment by nicki-krizek** [comment]
PR #3 fixes this issue. Please note that if you previously installed `DSTRootCAX3` you will most likely need to reinstall IPA before the fix will work for you.

**Comment by JoyceBabu** [comment]
It worked, thank you.

If anyone wants to use `dns-01` validation with Route53, you can use the `certbot-route53` plugin

```
dnf install -y git gcc libffi-devel redhat-rpm-config python-devel openssl-devel
pip install -U certbot-route53
```

Then modify `renew-le.sh` with

```
letsencrypt certonly --standalone --csr "$WORKDIR/httpd-csr.der" --email "$EMAIL" --agree-tos
```

```
DOMAIN="yourdomain.com"
certbot certonly  --csr "$WORKDIR/httpd-csr.der" --email "$EMAIL" --agree-tos -d "$DOMAIN" -a certbot-route53:auth
```

**Comment by jokogr** [comment]
@tomaskrizek I had previously installed `DSTRootCAX3`, so I have to reinstall IPA.

1. Am I going to lose the data if I reinstall it?
2. Any idea what the installation command would be? I am guessing it is going to be a CA-less installation, so I wonder what to include for CA, SSL certificate etc.

**Comment by ahharu** [comment]
I stumbled on this today... any clue?
