### ISSUE TITLE
setup-le.sh fails on CentOS8

### ISSUE THREAD

**Issue by happosade** [freeipa/freeipa-letsencrypt#17]
Looks like `setup-le.sh` fails on CentOS 8.

While running the `setup-le.sh`, I get following:

```bash
Error: 
 Problem: package certbot-1.3.0-3.el8.noarch requires python3-certbot = 1.3.0-3.el8, but none of the providers can be installed
  - conflicting requests
  - nothing provides python3-mock needed by python3-certbot-1.3.0-3.el8.noarch
  - nothing provides python3.6dist(mock) needed by python3-certbot-1.3.0-3.el8.noarch
```

When trying to run, it runs into problem of not being able to install certbot.
Seems similar to https://github.com/ansible/workshops/issues/768

**Comment by mkosek** [comment]
I was personally not testing/using these scripts with CentOS/RHEL-8. I saw some suggestions about what can be done for example here - https://serverfault.com/questions/975002/install-certbot-in-red-hat-enterprise-linux-8-manually

If you install certbot before running setup-le.sh, it should get past this step.
