### ISSUE TITLE
Freeipa installation

### ISSUE THREAD

**Issue by guillermocol** [freeipa/freeipa-letsencrypt#36]
Hello,

I am running on Debian the installation of Freeipa and I am getting the following error almost at the end of the installation after running:

# ipa-server-install --no-ntp

  [11/30]: starting certificate server instance
  [12/30]: configure certmonger for renewals
  [13/30]: requesting RA certificate from CA

[error] RuntimeError: Certificate issuance failed (CA_REJECTED: Server at "https://freeipa.******.com:8443/ca/agent/ca//profileProcess" replied: 1: You did not provide a valid certificate for this operation)
Certificate issuance failed (CA_REJECTED: Server at "https://freeipa.*****.com:8443/ca/agent/ca//profileProcess" replied: 1: You did not provide a valid certificate for this operation)
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

I am not sure if there is any relation with my host file configuration, though it is talking about the certificate in the following message.

Checking the freeipa logs I have got the following log in /var/log/ipaserver-install.log:

File "/usr/lib/python3/dist-packages/ipaserver/install/dogtaginstance.py", line 520, in handle_setup_error
    raise RuntimeError("%s configuration failed." % self.subsystem)

2021-04-10T17:00:51Z DEBUG The ipa-server-install command failed, exception: RuntimeError: CA configuration failed.
2021-04-10T17:00:51Z ERROR CA configuration failed.

Thank you for your help,

**Comment by abbra** [comment]
Hi @guillermocol. This is a wrong project to report such issue.

Please use freeipa-users@ mailing list to investigate your problem. You can start with a similar thread: https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/thread/6SK2ZRP2VJ77Z24S7U56ZVT3OT45VAMV/#AL332JQYNWGQBWG56QLMIHHGKANFPF3Y
