### ISSUE TITLE
renew-le.sh can't find httpd.crt in Centos7 and FreeIPA 4.6x

### ISSUE THREAD

**Issue by j4jes** [freeipa/freeipa-letsencrypt#37]
Where can I get version of renew-le.sh for my v4.6x FreeIPA install in Centos7 ? Thanks!

![image](https://user-images.githubusercontent.com/32603912/123383102-bed2e100-d560-11eb-9bae-b57a949e9a16.png)

**Comment by antonkobylko1990** [comment]
Hello! Same problem but with /var/lib/ipa/private/httpd.key

140676939933584:error:02001002:system library:fopen:No such file or directory:bss_file.c:402:fopen('/var/lib/ipa/private/httpd.key','r')
140676939933584:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
unable to load Private Key

**Comment by rcritten** [comment]
This script is not compatible with RHEL/CentOS 7. The web certificate 7 is stored in the NSS database in /etc/httpd/alias and not in discrete files.
