### ISSUE TITLE
Error opening Private Key /var/lib/ipa/private/httpd.key

### ISSUE THREAD

**Issue by jktrigg** [freeipa/freeipa-letsencrypt#39]
Error opening Private Key /var/lib/ipa/private/httpd.key
139845738243984:error:02001002:system library:fopen:No such file or directory:bss_file.c:402:fopen('/var/lib/ipa/private/httpd.key','r')
139845738243984:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
unable to load Private Key

Then it terminates without finishing.

Note that this is on Centos 7.

**Comment by jktrigg** [comment]
Specifically, after ipa-server-install, directory /var/lib/ipa/private/ does not exist, using ipa-server-4.6.8-5.el7.centos.7.x86_64.

**Comment by rcritten** [comment]
This script is does to not work in EL7.

RHEL 7 uses an NSS database to store the Apache certificate and private key and not discrete PEM files (mod_nss vs mod_ssl)
