### ISSUE TITLE
freeipa-letsencrypt fails on Centos 7 with FreeIPA 4.6.8

### ISSUE THREAD

**Issue by jktrigg** [freeipa/freeipa-letsencrypt#40]
Error opening Private Key /var/lib/ipa/private/httpd.key
139845738243984:error:02001002:system library:fopen:No such file or directory:bss_file.c:402:fopen('/var/lib/ipa/private/httpd.key','r')
139845738243984:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
unable to load Private Key

Then it terminates without finishing.

Note that this is on Centos 7.

**Comment by rcritten** [comment]
The same root cause as the other ticket you opened, https://github.com/freeipa/freeipa-letsencrypt/issues/39

This script doesn't work in RHEL/CentOS 7.
